### ISSUE TITLE
borders too big 

### ISSUE THREAD

**Issue by Aneeqasif** [nclarius/Plasma-window-decorations#4]
![image](https://user-images.githubusercontent.com/78728701/208238838-31c870ac-2245-4594-ae09-01f04bb27f3f.png)

**Comment by nclarius** [comment]
Do you use display scaling?

**Comment by Aneeqasif** [comment]
> 

yes

**Comment by nclarius** [comment]
In this case I'm afraid this is [bug #422598](https://bugs.kde.org/show_bug.cgi?id=422598), which can only be fixed upstream in the theming engine and not in this particular window decoration.

As a workaround you could try setting the border size smaller in the window decorations system settings or editing the SVG files (see README).

**Comment by nclarius** [comment]
Bismuth uses a different theming engine which isn't affected by this bug.

Not sure why OneDark doesn't have this problem though, thanks for pointing it out. I might look into it at some point, but since I don't use scaling myself, it's not high on my priority list.

For the files to edit, see https://github.com/nclarius/Plasma-window-decorations#configuration. Relevant variables are `BorderAB` in `ActiveAccentXYZrc ` which can open with an ordinary text editor, and the `width`/`height` properties for the `decoration-abc` elements in `decoration.svgz` which is most easily edited with a vector graphics editor such as Inkscape.
